name: 🚀 SIMPLE KOTUKTOPER BUILD

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      
    - name: 🏗️ Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace
        
    - name: 📦 Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: KotuktoperGram
        path: "**/*.apk"
